Financeiro/Models/BuscaMovimentacoesModel.cs
using Financeiro.Entidades;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Financeiro.Models
{
    public class BuscaMovimentacoesModel
    {
        public decimal? ValorMinimo{ get; set; }
        public decimal? ValorMaximo { get; set; }
        public DateTime? DataMinima { get; set; }
        public DateTime? DataMaxima { get; set; }
        public int? UsuarioId { get; set; }
        public Tipo? Tipo { get; set; }
        public IList<Movimentacao> Movimentacoes { get; set; }
        public IList<Usuario> Usuarios { get; set; }

    }
}

Financeiro/Models/MovimentacoesByUsuarioModel.cs
using Financeiro.Entidades;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Financeiro.Models
{
    public class MovimentacoesByUsuarioModel
    {
        public int? UsuarioId{ get; set; }

        public IList<Movimentacao> Movimentacoes{ get; set; }

        public IList<Usuario> Usuarios { get; set; }
    }
}

Financeiro/Models/UsuarioModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace Financeiro.Models
{
    public class UsuarioModel
    {
        [Required]
        public string Nome { get; set; }

        [Required, EmailAddress]
        public string Email { get; set; }

        [Required]
        public string Senha { get; set; }

        [Compare("Senha")]
        public string ConfirmacaoSenha { get; set; }
    }
}

Financeiro/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Financeiro.Controllers
{
    public class HomeController : Controller
    {
        // GET: Home
        public ActionResult Index()
        {
            return View();
        }
    }
}

Financeiro/Controllers/LoginController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebMatrix.WebData;

namespace Financeiro.Controllers
{
    public class LoginController : Controller
    {
        // GET: Login
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Autentica(String login, String senha)
        {
            if(WebSecurity.Login(login, senha))
            {
                return RedirectToAction("Index", "Home");
            }else
            {
                ModelState.AddModelError("login.invalido", "Login ou senha incorretos");
                return View("Index");
            }
        }

        public ActionResult Logout()
        {
            WebSecurity.Logout();
            return RedirectToAction("Index");
        }
    }
}

Financeiro/Controllers/MovimentacaoController.cs
using Financeiro.DAO;
using Financeiro.Entidades;
using Financeiro.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Financeiro.Controllers
{
    //Só tem acesso as Movimentações se estiver autenticado
    [Authorize]
    public class MovimentacaoController : Controller
    {
        private MovimentacaoDAO movimentacaoDAO;
        private UsuarioDAO usuarioDAO;

        public MovimentacaoController(MovimentacaoDAO movimentacaoDAO, UsuarioDAO usuarioDAO)
        {
            this.movimentacaoDAO = movimentacaoDAO;
            this.usuarioDAO = usuarioDAO;
        }
        public ActionResult Form()
        {
            ViewBag.Usuarios = usuarioDAO.Lista();
            return View();
        }

        public ActionResult Adiciona(Movimentacao movimentacao)
        {
            //Se o formulario está com todoos os campos validos
            if (ModelState.IsValid)
            {
                movimentacaoDAO.Adiciona(movimentacao);
                return RedirectToAction("Index");
            }
            else
            {
                ViewBag.Usuarios = usuarioDAO.Lista();
                return View("Form", movimentacao);
            }
        }

        public ActionResult Index()
        {
            IList<Movimentacao> movimentacoes = movimentacaoDAO.Lista();
            return View(movimentacoes);
        }

        public ActionResult MovimentacoesByUsuario(MovimentacoesByUsuarioModel model)
        {
            model.Usuarios = usuarioDAO.Lista();
            model.Movimentacoes = movimentacaoDAO.BuscaByUsuario(model.UsuarioId);
            return View(model);
        }

        public ActionResult Busca(BuscaMovimentacoesModel model)
        {
            model.Usuarios = usuarioDAO.Lista();
            model.Movimentacoes = movimentacaoDAO.Busca(model.ValorMinimo, model.ValorMaximo, model.DataMinima, model.DataMaxima, model.Tipo, model.UsuarioId);

            return View(model);
        }
    }
}

Financeiro/Controllers/UsuarioController.cs
using Financeiro.Entidades;
using Financeiro.DAO;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Financeiro.Models;
using WebMatrix.WebData;
using System.Web.Security;

namespace Financeiro.Controllers
{
    public class UsuarioController : Controller
    {
        private UsuarioDAO usuarioDAO;

        public UsuarioController(UsuarioDAO usuarioDAO)
        {
            this.usuarioDAO = usuarioDAO;
        }

        public ActionResult Form()
        {
            return View();
        }

        public ActionResult Adiciona(UsuarioModel model)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    WebSecurity.CreateUserAndAccount(model.Nome, model.Senha, new { Email = model.Email });
                    return RedirectToAction("Index");
                }
                catch (MembershipCreateUserException e)
                {
                    ModelState.AddModelError("usuario.Invalido", e.Message);
                    return View("Form", model);
                }

            }
            else
            {
                return View("form", model);
            }
        }

        public ActionResult Index()
        {
            IList<Usuario> usuarios = usuarioDAO.Lista();
            return View(usuarios);
        }
    }
}

Financeiro/Views/Home/Index.cshtml
Ola mundo!

Financeiro/Views/Login/Index.cshtml
<form action="@Url.Action("Autentica")" method="post">

    @Html.ValidationMessage("login.invalido")

    <label for="login">Login:</label>
    <input id="login" name="login" type="text" class="form-control" />

    <label for="senha">Senha:</label>
    <input id="senha" name="senha" type="password" class="form-control" />

    <input type="submit" value="Autenticar" />
</form>

Financeiro/Views/Movimentacao/Busca.cshtml
@model Financeiro.Models.BuscaMovimentacoesModel

@using(Html.BeginForm("Busca", "Movimentacao", FormMethod.Get))
{
    <div class="row">
        <fieldset>
            <legend>Data movimentacao</legend>
            <div class="col-sm-6">
                @Html.LabelFor(b => b.DataMinima, "Mínima")
                @Html.TextBoxFor(b => b.DataMinima, new { @class = "form-control" })
            </div>

            <div class="col-sm-6">
                @Html.LabelFor(b => b.DataMaxima, "Máxima")
                @Html.TextBoxFor(b => b.DataMaxima, new { @class = "form-control" })
            </div>
        </fieldset>

        <fieldset>
            <legend>Valor</legend>
            <div class="col-sm-6">
                @Html.LabelFor(b => b.ValorMinimo, "Mínimo")
                @Html.TextBoxFor(b => b.ValorMinimo, new { @class = "form-control" })
            </div>

            <div class="col-sm-6">
                @Html.LabelFor(b => b.ValorMaximo, "Máximo")
                @Html.TextBoxFor(b => b.ValorMaximo, new { @class = "form-control" })
            </div>
        </fieldset>

        <fieldset>
            <legend>Usuario e Tipo</legend>
            <div class="col-sm-6">
                @Html.LabelFor(b => b.Tipo, "Tipo")
                @Html.EnumDropDownListFor(b => b.Tipo, new { @class = "form-control" })
            </div>

            <div class="col-sm-6">
                @Html.LabelFor(b => b.UsuarioId, "Usuário")
                @Html.DropDownListFor(b => b.UsuarioId, new SelectList(Model.Usuarios, "Id", "Nome"), "Escolha um usuário")
            </div>
        </fieldset>

        <input type="submit" value="Buscar" />
    </div>
}

<table class="table table-hover">
    <thead>
        <tr>
            <th>Id</th>
            <th>Data</th>
            <th>Valor</th>
            <th>Tipo</th>
            <th>Usuario</th>
        </tr>
    </thead>
    <tbody>
        @foreach(var m in Model.Movimentacoes)
        {
        <tr>
            <td>@m.Id</td>
            <td>@m.Data</td>
            <td>@m.Valor</td>
            <td>@m.Tipo</td>
            <td>@m.Usuario</td>
        </tr>
        }
    </tbody>
</table>

Financeiro/Views/Movimentacao/Form.cshtml
@model Financeiro.Entidades.Movimentacao

@using (Html.BeginForm("Adiciona", "Movimentacao", FormMethod.Post))
{
    @Html.LabelFor(m => m.Valor, "valor")
    @Html.TextBoxFor(m => m.Valor, new { @class = "form-control" })
    @Html.ValidationMessageFor(m => m.Valor)

    @Html.LabelFor(m => m.UsuarioId, "Usuario: ")
    @Html.DropDownListFor(m => m.UsuarioId, new SelectList(ViewBag.Usuarios, "Id", "Nome"), new { @class = "form-control" })
    @Html.ValidationMessageFor(m => m.UsuarioId)

    @Html.LabelFor(m => m.Tipo, "Tipo: ")
    @Html.EnumDropDownListFor(m => m.Tipo, new { @class = "form-control" })
    @Html.ValidationMessageFor(m => m.Tipo)

    @Html.LabelFor(m => m.Data, "Data: ")
    @Html.TextBoxFor(m => m.Data, new { @class = "form-control" })
    @Html.ValidationMessageFor(m => m.Data)

    <input type="submit" value="Enviar" />
}

Financeiro/Views/Movimentacao/Index.cshtml
@model IList<Financeiro.Entidades.Movimentacao>

@Html.ActionLink("Nova movimentação", "Form", "Movimentacao")

<table class="table table-hover">
    <thead>
        <tr>
            <th>ID</th>
            <th>Usuario</th>
            <th>Valor</th>
            <th>Tipo</th>
        </tr>
    </thead>
    <tbody>
        @foreach(var m in Model)
        {
            <tr>
                <td>@m.Id</td>
                <td>@m.Usuario.Nome</td>
                <td>@m.Valor</td>
                <td>@m.Tipo</td>
            </tr>
        }
    </tbody>
</table>

Financeiro/Views/Movimentacao/MovimentacoesByUsuario.cshtml
@model Financeiro.Models.MovimentacoesByUsuarioModel

@using (Html.BeginForm("MovimentacoesByUsuario", "Movimentacao", FormMethod.Get))
{
    @Html.LabelFor(m => m.UsuarioId, "Usuário")
    @Html.DropDownListFor(
                            m => m.UsuarioId, 
                            new SelectList(Model.Usuarios, "Id", "Nome"), 
                            "Escolha um usuário"
                          )

    <input type="submit" value="Buscar" />
}

<table class="table table-hover">
    <thead>
        <tr>
            <th>Usuario</th>
            <th>Tipo</th>
            <th>Valor</th>
        </tr>
    </thead>

    <tbody>
        @foreach (var m in Model.Movimentacoes)
        {
            <tr>
                <td>@m.Usuario.Nome</td>
                <td>@m.Tipo</td>
                <td>@m.Valor</td>
            </tr>
        }
    </tbody>
</table>

Financeiro/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="~/App_Start/Content/Site.css" rel="stylesheet" type="text/css" />
    <link href="~/App_Start/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <title>@ViewBag.Title - My ASP.NET Application</title>

</head>
<body>
    @Html.Partial("_MenuSuperior")
    <div class="container">
        <main class="col-sm-8">
            @RenderBody()  
        </main>
        <aside class="col-sm-4">
            <h3>Acesso Rapido</h3>
            <ul>
                <li>@Html.ActionLink("Movimentacoes por usuario", "MovimentacoesByUsuario", "Movimentacao")</li>
                <li>@Html.ActionLink("Busca de movimentacoes", "Busca", "Movimentacao")</li>
            </ul>
        </aside>
    </div>
</body>
</html>

Financeiro/Views/Shared/_MenuSuperior.cshtml
<nav>
    <div class="container-fluid">
        <ul class="nav nav-tabs">
            <!-- ActionLink(texto, metodo, classe)-->
            <li>@Html.ActionLink("Home", "Index", "Home")</li>
            <li>@Html.ActionLink("Usuarios", "Index", "Usuario")</li>
            <li>@Html.ActionLink("Movimentacao", "Index", "Movimentacao")</li>

            <!-- ou WebSecurity.IsAuthenticated -->
            @if (User.Identity.IsAuthenticated)
            {
                <li>@Html.ActionLink("Sair", "Logout", "Login")</li>
            }
            else
            {
                <li>@Html.ActionLink("Autenticar", "Index", "Login")</li>
            }
        </ul>
    </div>
</nav>

Financeiro/Views/Usuario/Form.cshtml
@model Financeiro.Models.UsuarioModel

<!-- BeginForm(metodo, controller)-->
@using (Html.BeginForm("Adiciona", "Usuario", FormMethod.Post))
{
    @Html.ValidationMessage("usuario.Invalido")

    @Html.LabelFor(u => u.Nome, "Nome:")
    @Html.TextBoxFor(u => u.Nome, new { @class = "form-control" })
    @Html.ValidationMessageFor(u => u.Nome)

    @Html.LabelFor(u => u.Email, "Email:")
    @Html.TextBoxFor(u => u.Email, new { @class = "form-control" })
    @Html.ValidationMessageFor(u => u.Email)

    @Html.LabelFor(u => u.Senha, "Senha:")
    @Html.PasswordFor(u => u.Senha, new { @class = "form-control" })
    @Html.ValidationMessageFor(u => u.Senha)

    @Html.LabelFor(u => u.ConfirmacaoSenha, "Confirmar Senha:")
    @Html.PasswordFor(u => u.ConfirmacaoSenha, new { @class = "form-control" })
    @Html.ValidationMessageFor(u => u.ConfirmacaoSenha)

    <input type="submit" value="Enviar" />
}

Financeiro/Views/Usuario/Index.cshtml
@model IList<Financeiro.Entidades.Usuario>

@Html.ActionLink("Novo Usuario", "Form")

<table class="table table-hover">
    <thead>
        <tr>
            <th>Id</th>
            <th>Nome</th>
            <th>E-mail</th>
        </tr>
    </thead>
    <tbody>
        @foreach(var usuario in Model)
        {
        <tr>
            <td>@usuario.Id</td>
            <td>@usuario.Nome</td>
            <td>@usuario.Email</td>
        </tr>
        }
    </tbody>
</table>